[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "social-payments-account-registry"
version = "0.1.0"
authors = [
  { name="OpenG2P", email="info@openg2p.org" },
]
description = "Social Payments Account Registry"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
  "Programming Language :: Python :: 3",
  "License :: OSI Approved :: Mozilla Public License 2.0 (MPL 2.0)",
  "Operating System :: OS Independent",
]
dependencies=[
  "openg2p-fastapi-common",
  "openg2p-fastapi-auth",
]

[project.urls]
Homepage = "https://openg2p.org"
Documentation = "https://docs.openg2p.org/"
Repository = "https://github.com/OpenG2P/social-payments-account-registry"
Source = "https://github.com/OpenG2P/social-payments-account-registry"
