name: Publish to PyPI

on:
  release:
    types:
      - created

jobs:
  publish-to-pypi:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: Install build dependencies
      run: pip install build
    - name: Build distribution SPAR
      run: python -m build social-payments-account-registry
    - name: Publish SPAR
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        packages-dir: social-payments-account-registry/dist
        password: ${{ secrets.PYPI_API_TOKEN }}
    - name: Build distribution SPAR G2P Connect Backend
      run: python -m build spar-connector-g2pconnect
    - name: Publish SPAR G2P Connect Backend
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        packages-dir: spar-connector-g2pconnect/dist
        password: ${{ secrets.PYPI_API_TOKEN }}
    - name: Build distribution SPAR Mojaloop ALS Oracle
      run: python -m build spar-mojaloop-als-oracle
    - name: Publish SPAR Mojaloop ALS Oracle
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        packages-dir: spar-mojaloop-als-oracle/dist
        password: ${{ secrets.PYPI_API_TOKEN }}
    - name: Build distribution SPAR G2PConnect Mapper
      run: python -m build spar-g2pconnect-id-mapper
    - name: Publish SPAR G2PConnect Mapper
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        packages-dir: spar-g2pconnect-id-mapper/dist
        password: ${{ secrets.PYPI_API_TOKEN }}
